#travis configuration for coverage testing
language: cpp
sudo: false

os: linux
dist: trusty

compiler:
  - gcc

before_install:
  - sudo apt-get update

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - libopenmpi-dev
    - openmpi-bin

script:
  - source build.sh
  - mpirun -np 8 dataGen outputFile