#travis configuration for coverage testing
language: cpp
sudo: false

os: linux

compiler:
  - gcc

before_install:
  - sudo apt-get update

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - libopenmpi-dev
    - openmpi-bin

before_script: 
  - cd DataGenerator
  
script:
  - ls
  - source compile.sh
  - mpirun -np 8 dataGen outputFile