#travis configuration for coverage testing
language: cpp
sudo: false

os: linux
dist: trusty

compiler: g++

before_install:
  # C++14
  - sudo apt-get update

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
    - libopenmpi-dev
    - openmpi-bin

install:
  # C++14
  export CXX=gcc-7
  export CXX=g++-7


script:
  # C++14
  - source build.sh
  - mpirun -np 8 dataGen outputFile