#travis configuration for coverage testing
language: cpp
sudo: false

os: linux
dist: trusty

compiler:
  - gcc

before_install:
  # C++11
  - sudo apt-get update

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - libopenmpi-dev
    - openmpi-bin

install:
  export CXX="g++-6 -std=c++11"
  
script:
  # C++11
  - source build.sh
  - mpirun -np 8 dataGen outputFile